### ISSUE TITLE
Sin banderas en windows (Chrome)

### ISSUE THREAD

**Issue by ruiz16** [midudev/midu-timeszones-latam#1]
15H 🇪🇸
10H 🇺🇾 🇦🇷
9H 🇨🇱 🇵🇾 🇹🇹 🇧🇴 🇻🇪 🇩🇴
8H 🇨🇴 🇲🇽 🇵🇪 🇪🇨
7H 🇨🇷 🇳🇮 🇸🇻

Este es el resultado.

**Comment by midudev** [comment]
Tu comentario me sale así:
![image](https://user-images.githubusercontent.com/1561955/187795491-8fb86a45-cc4e-4cf3-866c-aee59c03611d.png)

jajajaja Pero ya me imagino que no salen en Windows. :) 

Igualmente al copiar el texto y ponerlo en un tuit, deberían salir correctamente.

**Comment by sdsoldi** [comment]
En windows (Firefox) yo también veo sus iconos

**Comment by midudev** [comment]
Arreglado!
